### ISSUE TITLE
[Feat] 회원가입 페이지 필수요구사항 기능 구현

### ISSUE THREAD

**Issue by ronieo** [today-zipsa/TodayZipsa#26]
- [x]  이메일주소 입력창이 있어야 한다.
    - [x]  이메일 양식 확인이 되어야 한다.
- [x]  비밀번호 및 비밀번호 확인 창이 있어야 한다.
    - [x]  비밀번호가 일치하지 않을 경우 알림 문구가 보여져야 한다.
- [x]  프로필 이미지 사진이 최대 1MB이하 사이즈로 업로드 가능해야 한다. #123
    - [x]  만약 사이즈가 클 경우 업로드 불가하다는 알림 모달창이 띄워져야 한다.

- [x]  필수 이용약관 동의 체크 버튼이 있어야 한다.
    - [x]  이용약관동의 글자를 글릭하면 이용약관 전문 모달창이 띄워져야 한다.
    - [x]  만약 필수 이용약관 동의를 체크하지 않은 경우 이용약관 동의에 체크해달라는 안내 모달창을 띄워야 한다.
    - [x]  필수 이용약관 동의를 체크하지 않는 경우엔 회원가입이 불가능해야 한다.
- [x]  개인정보 수집 동의 체크 버튼이 있어야 한다.
    - [x]  개인정보 수집 동의 글자를 클릭하면 개인정보 수집 약관 전문 모달창이 띄워져야 한다.
    - [x]  만약 개인정보 수집 동의를 체크하지 않은 경우 개인정보 수집 동의에 체크해달라는 안내 모달창을 띄워야 한다.
    - [x]  개인정보 수집 동의를 체크하지 않은 경우 회원가입이 불가능해야 한다.
- [x]  만 14세이상 인지 체크하는 버튼이 있어야 한다.
    - [x]  만약 체크하지 않은 경우 체크해달라는 안내 모달창이 띄워져야 한다.
    - [x]  체크하지 않은 경우 회원가입이 불가능 해야한다.
- [x]  필수 이용약관 동의 체크 상태값이 저장되어야 한다. #124 
- [x]  가입하기 버튼이 있어야 한다.
  - [x] 필수 이용약관 동의 체크 상태값이 모두 true인 경우 메인페이지로 이동해야 한다.
- [x]  가입하기 버튼을 클릭하면 로컬스토리지에 사용자 정보가 저장되어야 한다. #109 
- [x] 공통 헤더에서 로그인 된 상태가 보여져야 한다. #115  
- [x] navigo 구현 
- [x] join.js 모듈 실행이 정상적으로 되지 않는 문제 해결 #126
